name: aplicativo_praja
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^6.0.5
  http: ^1.2.2
  intl: ^0.17.0
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  firebase_core_web: ^2.10.0
  cupertino_icons: ^1.0.6
  cloud_firestore: ^5.4.0
  geolocator: ^12.0.0
  google_maps_flutter: ^2.9.0
  image_picker: ^1.1.2
  firebase_storage: ^12.2.0
  url_launcher: ^6.0.20
  google_fonts: ^6.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true
  assets:
    - assets/avatar.jpg
    - assets/workerlogo.png
    - assets/agora.png
    - assets/profileanon.jpeg
    - assets/anon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "images/pj_icon.png"
